name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  WORKING_DIRECTORY: Pokemon_Vanquish_Proj
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIRECTORY}}
    - name: Build
      run: dotnet build --no-restore ${{env.WORKING_DIRECTORY}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.WORKING_DIRECTORY}}
      
  docker-image-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        file: ${{env.WORKING_DIRECTORY}}/Dockerfile
        push: true
        tags: index.docker.io/${{secrets.DOCKER_USERNAME}}/pokemonvanquishproj:${{github.sha}}
  azure-deploy:
    runs-on: ubuntu-latest
    needs: docker-image-run
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: Vanquish-P2
        publish-profile: $${{secrets.AZURE_PUBLISH}}
        images: ${{secrets.DOCKER_USERNAME}}/pokemonvanquishproj:${{github.sha}}

