name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  WORKING_DIRECTORY: Pokemon\ Vanquis\ Proj
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.WORKING_DIRECTORY}}
    - name: Build
      run: dotnet build --no-restore ${{env.WORKING_DIRECTORY}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.WORKING_DIRECTORY}}
      
  docker-image-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
      uses: docker/setup-buildx-action@v2.0.0
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{secrets.DOCKER_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
      uses: docker/build-push-action@v3.0.0
      with:
        context: ${{env.WORKING_DIRECTORY}}
        file: ${{env.WORKING_DIRECTORY}}/Dockerfile
        push: true
        tags: index.docker.io/${{secrets.DOCKER_USERNAME}}/pokemonvanquishproj:${{github.sha}}
    
